from datetime import datetime
from typing import Any


def _iso(value: str) -> str:
    return datetime.fromisoformat(value).isoformat()


DEMO_FEEDBACK_FIXTURES: dict[str, list[dict[str, Any]]] = {
    "fitness_app": [
        {
            "raw_text": "The workout plans are great, but my Apple Watch sync drops at least twice a week.",
            "normalized_text": "Workout plans are strong but Apple Watch sync is unreliable.",
            "rating": 3,
            "feedback_date": _iso("2026-04-02T09:15:00+00:00"),
            "author_handle": "runnerjess",
            "metadata_json": {"channel": "app_store", "topic": "device_sync"},
        },
        {
            "raw_text": "Please add more beginner strength sessions under 20 minutes.",
            "normalized_text": "User wants more short beginner strength sessions.",
            "rating": 4,
            "feedback_date": _iso("2026-04-05T14:10:00+00:00"),
            "metadata_json": {"channel": "survey", "topic": "content_library"},
        },
        {
            "raw_text": "The subscription price feels high when the live classes buffer on hotel Wi-Fi.",
            "normalized_text": "Subscription price feels expensive when live classes buffer.",
            "rating": 2,
            "feedback_date": _iso("2026-04-08T18:22:00+00:00"),
            "metadata_json": {"channel": "app_store", "topic": "pricing"},
        },
        {
            "raw_text": "Love the streak reminders. They actually keep me on track.",
            "normalized_text": "Streak reminders are motivating and effective.",
            "rating": 5,
            "feedback_date": _iso("2026-04-11T07:30:00+00:00"),
            "metadata_json": {"channel": "in_app_nps", "topic": "engagement"},
        },
        {
            "raw_text": "Calories burned looks way off for cycling workouts compared with my bike computer.",
            "normalized_text": "Cycling calorie estimates appear inaccurate compared to external devices.",
            "rating": 2,
            "feedback_date": _iso("2026-04-12T16:55:00+00:00"),
            "metadata_json": {"channel": "support_ticket", "topic": "tracking_accuracy"},
        },
        {
            "raw_text": "The meditation audio keeps playing after I end the session.",
            "normalized_text": "Meditation audio does not stop when a session ends.",
            "rating": 2,
            "feedback_date": _iso("2026-04-14T13:05:00+00:00"),
            "metadata_json": {"channel": "support_ticket", "topic": "playback_bug"},
        },
        {
            "raw_text": "Family plan would make this much easier to justify.",
            "normalized_text": "User requests a family subscription plan.",
            "rating": 3,
            "feedback_date": _iso("2026-04-16T11:48:00+00:00"),
            "metadata_json": {"channel": "community_forum", "topic": "pricing"},
        },
        {
            "raw_text": "Coach audio cues are excellent during interval runs.",
            "normalized_text": "Coach audio cues are helpful in interval runs.",
            "rating": 5,
            "feedback_date": _iso("2026-04-18T06:42:00+00:00"),
            "metadata_json": {"channel": "in_app_nps", "topic": "coaching"},
        },
        {
            "raw_text": "Offline downloads fail if I switch from Wi-Fi to cellular mid-download.",
            "normalized_text": "Offline download flow fails when network changes mid-download.",
            "rating": 2,
            "feedback_date": _iso("2026-04-19T20:17:00+00:00"),
            "metadata_json": {"channel": "support_ticket", "topic": "offline_mode"},
        },
        {
            "raw_text": "Would love better monthly progress charts for pace and distance.",
            "normalized_text": "User wants stronger monthly progress visualization.",
            "rating": 4,
            "feedback_date": _iso("2026-04-22T15:00:00+00:00"),
            "metadata_json": {"channel": "survey", "topic": "analytics"},
        },
        {
            "raw_text": "The social feed is noisy. I mostly want to see close friends, not everyone.",
            "normalized_text": "Social feed needs better filtering for close friends.",
            "rating": 3,
            "feedback_date": _iso("2026-04-24T10:20:00+00:00"),
            "metadata_json": {"channel": "app_store", "topic": "social_features"},
        },
        {
            "raw_text": "Setup with my heart rate strap took two tries, but it’s solid after that.",
            "normalized_text": "Heart rate strap setup is a little confusing but stable afterward.",
            "rating": 4,
            "feedback_date": _iso("2026-04-25T12:12:00+00:00"),
            "metadata_json": {"channel": "survey", "topic": "device_setup"},
        },
    ],
    "crm_tool": [
        {
            "raw_text": "Bulk editing contacts is still too slow when we’re cleaning up event leads.",
            "normalized_text": "Bulk editing contacts is slow for large lead cleanup tasks.",
            "rating": 2,
            "feedback_date": _iso("2026-04-03T17:10:00+00:00"),
            "metadata_json": {"channel": "support_ticket", "topic": "contact_management"},
        },
        {
            "raw_text": "Pipeline board is clean, but drag-and-drop sometimes resets my filters.",
            "normalized_text": "Dragging deals in the pipeline board can reset filters.",
            "rating": 3,
            "feedback_date": _iso("2026-04-04T09:45:00+00:00"),
            "metadata_json": {"channel": "app_store", "topic": "pipeline_ux"},
        },
        {
            "raw_text": "The Gmail sync setup was surprisingly smooth.",
            "normalized_text": "Gmail sync setup is smooth and easy.",
            "rating": 5,
            "feedback_date": _iso("2026-04-06T13:18:00+00:00"),
            "metadata_json": {"channel": "survey", "topic": "integrations"},
        },
        {
            "raw_text": "Reporting is missing a simple way to compare rep performance week over week.",
            "normalized_text": "Reporting needs easier week-over-week rep performance comparisons.",
            "rating": 3,
            "feedback_date": _iso("2026-04-09T16:05:00+00:00"),
            "metadata_json": {"channel": "survey", "topic": "reporting"},
        },
        {
            "raw_text": "Please let admins lock required fields by stage. Reps keep skipping next-step notes.",
            "normalized_text": "Admins need required fields by pipeline stage.",
            "rating": 4,
            "feedback_date": _iso("2026-04-10T20:02:00+00:00"),
            "metadata_json": {"channel": "community_forum", "topic": "pipeline_rules"},
        },
        {
            "raw_text": "Duplicate detection helped, but imported company names still create messy records.",
            "normalized_text": "Duplicate detection is helpful but imports still create messy company records.",
            "rating": 3,
            "feedback_date": _iso("2026-04-13T11:12:00+00:00"),
            "metadata_json": {"channel": "support_ticket", "topic": "data_quality"},
        },
        {
            "raw_text": "The mobile app is okay for quick updates, but notes lag on poor reception.",
            "normalized_text": "Mobile note sync is slow on weak networks.",
            "rating": 3,
            "feedback_date": _iso("2026-04-15T07:55:00+00:00"),
            "metadata_json": {"channel": "app_store", "topic": "mobile_performance"},
        },
        {
            "raw_text": "Sequence analytics are exactly what our SDR manager needed.",
            "normalized_text": "Sequence analytics provide strong value for SDR management.",
            "rating": 5,
            "feedback_date": _iso("2026-04-17T18:40:00+00:00"),
            "metadata_json": {"channel": "in_app_nps", "topic": "automation"},
        },
        {
            "raw_text": "Onboarding took too many clicks before we could import our first deal list.",
            "normalized_text": "Onboarding has too many steps before first import.",
            "rating": 2,
            "feedback_date": _iso("2026-04-18T14:14:00+00:00"),
            "metadata_json": {"channel": "survey", "topic": "onboarding"},
        },
        {
            "raw_text": "Need better Slack notifications for deals that go stale.",
            "normalized_text": "Users want stronger Slack alerts for stale deals.",
            "rating": 4,
            "feedback_date": _iso("2026-04-20T10:03:00+00:00"),
            "metadata_json": {"channel": "community_forum", "topic": "notifications"},
        },
        {
            "raw_text": "Permissions are confusing when managers need visibility but not edit access.",
            "normalized_text": "Permissions model is confusing for manager visibility scenarios.",
            "rating": 2,
            "feedback_date": _iso("2026-04-23T15:49:00+00:00"),
            "metadata_json": {"channel": "support_ticket", "topic": "permissions"},
        },
        {
            "raw_text": "Forecast dashboard loads fast and looks polished.",
            "normalized_text": "Forecast dashboard performs well and feels polished.",
            "rating": 5,
            "feedback_date": _iso("2026-04-25T08:08:00+00:00"),
            "metadata_json": {"channel": "in_app_nps", "topic": "forecasting"},
        },
    ],
    "productivity_tool": [
        {
            "raw_text": "Notifications are too aggressive. I get pinged for minor status changes all day.",
            "normalized_text": "Notification volume is too high for minor task updates.",
            "rating": 2,
            "feedback_date": _iso("2026-04-01T08:20:00+00:00"),
            "metadata_json": {"channel": "app_store", "topic": "notifications"},
        },
        {
            "raw_text": "The new project templates helped our onboarding a lot.",
            "normalized_text": "Project templates improve team onboarding.",
            "rating": 5,
            "feedback_date": _iso("2026-04-03T12:10:00+00:00"),
            "metadata_json": {"channel": "in_app_nps", "topic": "templates"},
        },
        {
            "raw_text": "Dashboard widgets are too rigid. I want to resize and reorder everything.",
            "normalized_text": "Dashboard widgets need more customization and layout control.",
            "rating": 3,
            "feedback_date": _iso("2026-04-05T16:55:00+00:00"),
            "metadata_json": {"channel": "survey", "topic": "dashboards"},
        },
        {
            "raw_text": "Task comments disappear if I go offline on the train.",
            "normalized_text": "Offline comment drafts can be lost during connectivity changes.",
            "rating": 2,
            "feedback_date": _iso("2026-04-07T19:33:00+00:00"),
            "metadata_json": {"channel": "support_ticket", "topic": "offline_mode"},
        },
        {
            "raw_text": "Cross-project search is fast, which saves me a lot of time.",
            "normalized_text": "Cross-project search is fast and valuable.",
            "rating": 5,
            "feedback_date": _iso("2026-04-09T10:44:00+00:00"),
            "metadata_json": {"channel": "in_app_nps", "topic": "search"},
        },
        {
            "raw_text": "Recurring tasks are buried in settings. We almost missed the feature.",
            "normalized_text": "Recurring task setup is hard to discover.",
            "rating": 3,
            "feedback_date": _iso("2026-04-11T14:27:00+00:00"),
            "metadata_json": {"channel": "community_forum", "topic": "discoverability"},
        },
        {
            "raw_text": "Mobile app loads slowly when a project has lots of attachments.",
            "normalized_text": "Mobile performance degrades on projects with many attachments.",
            "rating": 2,
            "feedback_date": _iso("2026-04-13T09:05:00+00:00"),
            "metadata_json": {"channel": "app_store", "topic": "mobile_performance"},
        },
        {
            "raw_text": "Please give us quieter default notification settings for new team members.",
            "normalized_text": "New users need quieter default notification settings.",
            "rating": 3,
            "feedback_date": _iso("2026-04-15T18:41:00+00:00"),
            "metadata_json": {"channel": "survey", "topic": "notifications"},
        },
        {
            "raw_text": "The timeline view is great for weekly planning.",
            "normalized_text": "Timeline view is effective for weekly planning.",
            "rating": 5,
            "feedback_date": _iso("2026-04-18T07:14:00+00:00"),
            "metadata_json": {"channel": "in_app_nps", "topic": "planning"},
        },
        {
            "raw_text": "Permissions for guest collaborators are still confusing.",
            "normalized_text": "Guest collaborator permissions remain confusing.",
            "rating": 2,
            "feedback_date": _iso("2026-04-20T13:31:00+00:00"),
            "metadata_json": {"channel": "support_ticket", "topic": "permissions"},
        },
        {
            "raw_text": "Automation rules are powerful, but the error messages are too vague.",
            "normalized_text": "Automation rule errors need clearer messaging.",
            "rating": 3,
            "feedback_date": _iso("2026-04-22T11:52:00+00:00"),
            "metadata_json": {"channel": "community_forum", "topic": "automation"},
        },
        {
            "raw_text": "Comment mentions work well, but I'd like better control over who gets notified.",
            "normalized_text": "Mentions work, but notification targeting needs refinement.",
            "rating": 4,
            "feedback_date": _iso("2026-04-24T15:06:00+00:00"),
            "metadata_json": {"channel": "survey", "topic": "notifications"},
        },
    ],
}
